config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  mount RailsAdmin::Engine => '/railsadmin', as: 'rails_admin'
  devise_for :users

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root 'cars#home'

  get 'finance.php' => redirect('cars/financing/bussiness')
  get 'finance-form.php', controller: :cars, action: :finance_ash_car

  resources :cars do
    collection do
      get :search
      post :search
      get :nieuw_binnen
      get 'financing/:type', to: :financing, as: :financing
      get :voorraad, action: :index
      get 'finance_ash_car/:car/:type', to: 'cars#finance_ash_car'
    end
  end

  resources :brands do
    collection do
      post :models
    end
    resource :cars do
      get :index, to: 'cars#brand'
    end
  end

  resources :models do
    resource :cars do
      get :index, to: 'cars#model'
    end
  end

  resource :faqs do
    get :index
  end

  resource :wizard do
    post :pick_a_car
    get :pick_a_car
    post :your_details
    post :final
  end

  resources :pages, only: [:show] do
    collection do
      get :contact
      get :sitemap
    end
  end

  resources :blog_pages do
    collection do
      get :auto_blog
      get :auto_lease_mogelijkheden
      get :auto_op_afbetaling
      get :full_operational_lease
      get :lease_gebruikte_autos
      get :opel_eyetracking
      get :our_workspace
      get :voordelen_financial_lease
    end
  end

  resources :action_pages, path: :action, only: [:show]

  resources :blog_pages, as: :blog, only: [:show]

  resources :references, only: [:index, :create]

  namespace :admin do
    resource :admin do
      get :home
    end

    resources :action_pages

    resources :cars, only: [:index, :destroy]
    resources :static_texts do
      collection do
        put :update_multiple
      end
    end
    resources :faqs
    resources :pages
    resources :blog_pages do
      collection do
        get 'new/:template', action: :new, as: :new_with_template
        get 'edit/:id/:template', action: :edit, as: :edit_with_template
      end
    end

    resources :top_reviews

    resources :brands

    resources :banners, path: :banner do
      post :update_row_order, on: :collection
    end

    resources :references, only: [:index, :destroy] do
      collection do
        get '/approve/:id', action: :approve, as: :approve
        get '/disapprove/:id', action: :disapprove, as: :disapprove
      end
    end

    resources :menu_items do
      collection do
        put :update_all
      end
    end

    resources :cms_fields, only: [:index, :update]

    resources :car_requests, only: [:index, :show, :destroy] do
      get :show_bussiness
      delete :destroy_bussiness
    end

    root 'static_texts#index'
  end

  post '/import', to: 'import#handle'

end

app/models/action_page.rb
class ActionPage < ActiveRecord::Base

  extend FriendlyId
  friendly_id :banner_title, use: [:slugged, :finders]

  belongs_to :brand
  belongs_to :model

  attr_accessor :banner_image_cache
  attr_accessor :orange_banner_image_cache
  attr_accessor :reference_image_cache
  attr_accessor :reference_car_image_cache

  scope :active_actions, -> { where(active: true) }

  before_save :ensure_one_active_record
  before_save :ensure_model_matches_brand

  validates :banner_image, :banner_title, :header_title, :header_text, :car_section_title, :car_section_subtitle, presence: true
  validates_presence_of :orange_banner_image, :orange_banner_title, :orange_banner_text, if: lambda { orange_banner_enabled? }
  validates_presence_of :reference_image, :reference_text, :reference_stars, :reference_car_image, if: lambda { reference_banner_enabled? }

  def ensure_one_active_record
    if self.active?
      ActionPage.all.where.not(id: self.id).update_all(active: false)
    end
  end

  def ensure_model_matches_brand
    if self.brand != self.model.try(:brand)
      self.model = nil
    end
  end

  mount_uploader :banner_image, ActionPageUploader
  mount_uploader :orange_banner_image, ActionPageUploader
  mount_uploader :reference_image, ActionPageUploader
  mount_uploader :reference_car_image, ActionPageUploader


  def self.active_action
    active_actions.first
  end

  def should_generate_new_friendly_id?
    slug.blank?
  end

  def cars
    if model.present?
      model.cars
    elsif brand.present?
      brand.cars
    else
      Car.all
    end
  end

end

app/controllers/action_pages_controller.rb
class ActionPagesController < ApplicationController

  add_breadcrumb 'Acties'

  def show
    @action_page = ActionPage.find(params[:id])
    @cars = @action_page.cars.includes(:brand, :model).order(order_hash).page(params[:page]).per(8) if @action_page.present?
    add_breadcrumb @action_page.banner_title
  end

end

app/controllers/admin/action_pages_controller.rb
module Admin
  class ActionPagesController < AdminBaseController

    before_action :set_action_page, only: [:show, :edit, :destroy, :update]

    def index
      @action_pages = ActionPage.all
    end

    def new
      @action_page = ActionPage.new
    end

    def create
      @action_page = ActionPage.create(action_page_params)
      if @action_page.valid?
        flash[:notice] = ['ActionPage has been created succesfully']
        render :edit
      else
        flash[:error] = @action_page.errors.full_messages
        render :new
      end
    end

    def edit

    end

    def update
      begin
        @action_page.update action_page_params
        if @action_page.valid?
          flash[:notice] = ['ActionPage has been updated succesfully']
          redirect_to admin_action_pages_path
        else
          flash[:error] = @action_page.errors.full_messages
          render :edit
        end
      rescue
        flash[:error] = ['Some fields were not correct, please correct them and try again.']
        render :edit
      end
    end

    def destroy
      if @action_page.destroy
        flash[:notice] = ['The page has been deleted.']
      else
        flash[:error] = ['The page was not deleted']
      end
      redirect_to admin_action_pages_path
    end

    private

    def set_action_page
      begin
        @action_page = ActionPage.find(params[:id])
      rescue
        flash[:error] = ['ActionPage could not be found.']
        redirect_to admin_action_pages_path
      end
    end

    def action_page_params
      params.require(:action_page).permit(:id, :banner_title, :slug, :banner_subtitle, :banner_image, :banner_image_cache, :brand_id, :model_id, :active, :header_title, :header_text, :car_section_title, :car_section_subtitle, :orange_banner_enabled, :orange_banner_image, :orange_banner_title, :orange_banner_text, :pros_list_enabled, :reference_banner_enabled, :reference_image, :reference_stars, :reference_text, :reference_car_image, :reference_header, :reference_subtitle, :pro_1, :pro_2, :pro_3, :pro_4, :pro_5, :pro_6, :pro_7)
    end

  end
end

app/views/admin/action_pages/_form.html.erb
<div class="form-group form-group-default">
  <%= f.label :active %>
  <%= f.check_box :active, class: 'switchery' %>
</div>

<h2>General action info</h2>

<div class="form-group form-group-default">
  <%= f.label :banner_title %>
  <%= f.text_field :banner_title, class: 'form-control', required: true %>
</div>

<div class="form-group form-group-default">
  <%= f.label :slug %>
  <%= f.text_field :slug, class: 'form-control' %>
</div>

<div class="form-group form-group-default">
  <%= f.label :banner_image %>
  <%= f.file_field :banner_image, class: 'form-control' %>
  <%= f.hidden_field :banner_image_cache %>
  <%= image_tag f.object.banner_image.try(:admin) if f.object.banner_image.present? %>
</div>

<div class="form-group form-group-default">
  <%= f.label :brand_id %>
  <%= f.collection_select :brand_id, Brand.all.push(Brand.new({id: nil, name: 'Geen merk'})), :id, :name, {include_blank: true}, class: 'full-width', data: {'init-plugin' => 'select2'}, required: false %>
</div>

<% if f.object.brand %>
    <div class="form-group form-group-default">
      <%= f.label :model_id %>
      <%= f.collection_select :model_id, f.object.brand.models.order(name: :asc), :id, :name, {include_blank: true}, class: 'full-width model-select', required: false %>
    </div>
<% end %>

<div class="form-group form-group-default">
  <%= f.label :header_title %>
  <%= f.text_area :header_title, class: 'wysiwyg form-control', placeholder: 'Type something..', style: 'height: 250px;', required: true %>
</div>

<div class="form-group form-group-default">
  <%= f.label :header_text %>
  <%= f.text_area :header_text, class: 'wysiwyg form-control', placeholder: 'Type something..', style: 'height: 250px;', required: true %>
</div>

<h2>Cars section</h2>

<div class="form-group form-group-default">
  <%= f.label :car_section_title %>
  <%= f.text_field :car_section_title, class: 'form-control', required: true %>
</div>

<div class="form-group form-group-default">
  <%= f.label :car_section_subtitle %>
  <%= f.text_area :car_section_subtitle, class: 'wysiwyg form-control', placeholder: 'Type something..', style: 'height: 250px;', required: true %>
</div>

<h2>Orange banner</h2>

<div class="form-group form-group-default">
  <%= f.label :orange_banner_enabled %>
  <%= f.check_box :orange_banner_enabled, class: 'switchery' %>
</div>

<div class="form-group form-group-default">
  <%= f.label :orange_banner_image %>
  <%= f.file_field :orange_banner_image, class: 'form-control' %>
  <%= f.hidden_field :orange_banner_image_cache %>
  <%= image_tag f.object.orange_banner_image.try(:admin) if f.object.orange_banner_image.present? %>
</div>

<div class="form-group form-group-default">
  <%= f.label :orange_banner_title %>
  <%= f.text_field :orange_banner_title, class: 'form-control' %>
</div>

<div class="form-group form-group-default">
  <%= f.label :orange_banner_text %>
  <%= f.text_area :orange_banner_text, class: 'wysiwyg form-control', placeholder: 'Type something..', style: 'height: 250px;' %>
</div>

<h2>Lijst met voordelen AKP</h2>

<div class="form-group form-group-default">
  <%= f.label :pros_list_enabled %>
  <%= f.check_box :pros_list_enabled, class: 'switchery' %>
</div>

  <div class="form-group form-group-default col-md-6">
    <%= f.label :pro_1 %>
    <%= f.text_field :pro_1, class: 'form-control' %>
  </div>
  <div class="form-group form-group-default col-md-6">
    <%= f.label :pro_2 %>
    <%= f.text_field :pro_2, class: 'form-control' %>
  </div>
  <div class="form-group form-group-default col-md-6">
    <%= f.label :pro_3 %>
    <%= f.text_field :pro_3, class: 'form-control' %>
  </div>
  <div class="form-group form-group-default col-md-6">
    <%= f.label :pro_4 %>
    <%= f.text_field :pro_4, class: 'form-control' %>
  </div>
  <div class="form-group form-group-default col-md-6">
    <%= f.label :pro_5 %>
    <%= f.text_field :pro_5, class: 'form-control' %>
  </div>
  <div class="form-group form-group-default col-md-6">
    <%= f.label :pro_6 %>
    <%= f.text_field :pro_6, class: 'form-control' %>
  </div>
  <div class="form-group form-group-default col-md-6">
    <%= f.label :pro_7 %>
    <%= f.text_field :pro_7, class: 'form-control' %>
  </div>

<br>

<h2>Referentie</h2>

<div class="form-group form-group-default">
  <%= f.label :reference_banner_enabled %>
  <%= f.check_box :reference_banner_enabled, class: 'switchery' %>
</div>

<div class="form-group form-group-default">
  <%= f.label :reference_header %>
  <%= f.text_field :reference_header, class: 'form-control' %>
</div>

<div class="form-group form-group-default">
  <%= f.label :reference_subtitle %>
  <%= f.text_field :reference_subtitle, class: 'form-control' %>
</div>

<div class="form-group form-group-default">
  <%= f.label :reference_image %>
  <%= f.file_field :reference_image, class: 'form-control' %>
  <%= f.hidden_field :reference_image_cache %>
  <%= image_tag f.object.reference_image.try(:admin) if f.object.reference_image.present? %>
</div>

<div class="form-group form-group-default">
  <%= f.label :reference_stars %>
  <%= f.select :reference_stars, (1..5), {include_blank: false}, data: {'init-plugin' => 'select2'} %>
</div>

<div class="form-group form-group-default">
  <%= f.label :reference_text %>
  <%= f.text_area :reference_text, class: 'wysiwyg form-control', placeholder: 'Type something..', style: 'height: 250px;' %>
</div>

<div class="form-group form-group-default">
  <%= f.label :reference_car_image %>
  <%= f.file_field :reference_car_image, class: 'form-control' %>
  <%= f.hidden_field :reference_car_image_cache %>
  <%= image_tag f.object.reference_car_image.try(:admin) if f.object.reference_car_image.present? %>
</div>

<% content_for :footer do %>
    <script type="text/javascript" charset="utf-8">
        var elems = Array.prototype.slice.call(document.querySelectorAll('.switchery'));
        // Success color: #10CFBD
        elems.forEach(function (html) {
            var switchery = new Switchery(html, {color: '#10CFBD'});
        });
        $(document).ready(function () {
            // Avoid applying plugin to <select> with data-init-plugin="select2"

            // Only apply on elements that don't have data-init-plugin="select2"
            $(".model-select").select2({
                placeholder: "Select a model",
                allowClear: true
            });

            $('.wysiwyg').wysihtml5();

        });
    </script>
<% end %>

app/views/admin/action_pages/edit.html.erb
<!-- START PAGE COVER -->
<div class="container-fluid container-fixed-lg ">
  <ul class="breadcrumb">
    <li>
      <p><%= link_to 'Home', admin_root_path %></p>
    </li>
    <li><a href="" class="active">Edit Action Page</a></li>
  </ul>
  <!-- END BREADCRUMB -->
  <h3 class="page-title">Edit Action Page</h3>
</div>

<div class="container-fluid container-fixed-lg">
  <%= form_for @action_page, url: admin_action_page_path(@action_page), html: {class: 'form'} do |f| %>
      <%= render partial: 'admin/action_pages/form', locals: {f: f} %>
      <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

<% content_for :footer do %>
    <script>
        $(document).ready(function() {
            $('#wysiwyg5').wysihtml5();
        });
    </script>
<% end %>

app/views/admin/action_pages/index.html.erb
<!-- START PAGE COVER -->
<div class="container-fluid container-fixed-lg ">
  <ul class="breadcrumb">
    <li>
      <p><%= link_to 'Home', admin_root_path %></p>
    </li>
    <li><a href="#" class="active">Action Page's</a></li>
  </ul>
  <!-- END BREADCRUMB -->
  <h3 class="page-title">Action Pages</h3>
  <%= link_to 'New Action Page', new_admin_action_page_path %>
</div>

<div class="container-fluid container-fixed-lg">
      <table id="myDataTable" class="table table-hover" cellspacing="0" width="100%">
        <thead>
        <tr>
          <th>Title</th>
          <th>Slug</th>
          <th>Brand</th>
          <th>Model</th>
          <th>Active</th>
        </tr>
        </thead>
        <tbody>
        <% @action_pages.each do |action_page| %>
            <tr>
              <td><%= action_page.banner_title %></td>
              <td><%= action_page.slug %></td>
              <td><%= action_page.brand.try(:name) || 'Alle autos' %></td>
              <td><%= action_page.try(:model).try(:name) %></td>
              <td><%= action_page.active? %></td>
              <td>
                <%= link_to 'View', action_page_path(action_page), class: 'btn btn-primary', target: :blank %>
                <%= link_to 'Edit', edit_admin_action_page_path(action_page), class: 'btn btn-info' %>
                <%= link_to 'Delete', admin_action_page_path(action_page), confirm: 'Are you sure you want to delete this action_page?', method: :delete, class: 'btn btn-danger' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
</div>

<% content_for :footer do %>
<% end %>

app/views/admin/action_pages/new.html.erb
<!-- START PAGE COVER -->
<div class="container-fluid container-fixed-lg ">
  <ul class="breadcrumb">
    <li>
      <p><%= link_to 'Home', admin_root_path %></p>
    </li>
    <li><a href="" class="active">New Action Page</a></li>
  </ul>
  <!-- END BREADCRUMB -->
  <h3 class="page-title">New Action Page</h3>
</div>

<div class="container-fluid container-fixed-lg">
  <%= form_for @action_page, url: {action: :create}, html: {class: 'form'} do |f| %>
      <%= render partial: 'admin/action_pages/form', locals: {f: f} %>
      <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

<% content_for :footer do %>
    <script>
        $(document).ready(function() {
            $('#wysiwyg5').wysihtml5();
        });
    </script>
<% end %>