config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  mount RailsAdmin::Engine => '/railsadmin', as: 'rails_admin'
  devise_for :users

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root 'cars#home'

  get 'finance.php' => redirect('cars/financing/bussiness')
  get 'finance-form.php', controller: :cars, action: :finance_ash_car

  resources :cars do
    collection do
      get :search
      post :search
      get :nieuw_binnen
      get 'financing/:type', to: :financing, as: :financing
      get :voorraad, action: :index
      get 'finance_ash_car/:car/:type', to: 'cars#finance_ash_car'
    end
  end

  resources :brands do
    collection do
      post :models
    end
    resource :cars do
      get :index, to: 'cars#brand'
    end
  end

  resources :models do
    resource :cars do
      get :index, to: 'cars#model'
    end
  end

  resource :faqs do
    get :index
  end

  resource :wizard do
    post :pick_a_car
    get :pick_a_car
    post :your_details
    post :final
  end

  resources :pages, only: [:show] do
    collection do
      get :contact
      get :sitemap
    end
  end

  resources :blog_pages do
    collection do
      get :auto_blog
      get :auto_lease_mogelijkheden
      get :auto_op_afbetaling
      get :full_operational_lease
      get :lease_gebruikte_autos
      get :opel_eyetracking
      get :our_workspace
      get :voordelen_financial_lease
    end
  end

  resources :action_pages, path: :action, only: [:show]

  resources :blog_pages, as: :blog, only: [:show]

  resources :references, only: [:index, :create]

  namespace :admin do
    resource :admin do
      get :home
    end

    resources :action_pages

    resources :cars, only: [:index, :destroy]
    resources :static_texts do
      collection do
        put :update_multiple
      end
    end
    resources :faqs
    resources :pages
    resources :blog_pages do
      collection do
        get 'new/:template', action: :new, as: :new_with_template
        get 'edit/:id/:template', action: :edit, as: :edit_with_template
      end
    end

    resources :top_reviews

    resources :brands

    resources :banners, path: :banner do
      post :update_row_order, on: :collection
    end

    resources :references, only: [:index, :destroy] do
      collection do
        get '/approve/:id', action: :approve, as: :approve
        get '/disapprove/:id', action: :disapprove, as: :disapprove
      end
    end

    resources :menu_items do
      collection do
        put :update_all
      end
    end

    resources :cms_fields, only: [:index, :update]

    resources :car_requests, only: [:index, :show, :destroy] do
      get :show_bussiness
      delete :destroy_bussiness
    end

    root 'static_texts#index'
  end

  post '/import', to: 'import#handle'

end

app/models/brand.rb
class Brand < ActiveRecord::Base

  extend FriendlyId

  friendly_id :name, use: [:slugged, :finders]

  has_many :cars
  has_many :models, dependent: :destroy

  validates_presence_of :name
  validates_uniqueness_of :name

  def self.all_for_menu
    distinct.joins(:cars).group('brands.id').having('count(cars.id) > ?', 0).order('name asc')
  end

end

app/controllers/admin/brands_controller.rb
module Admin
  class BrandsController < AdminBaseController
    def index
      @brands = Brand.all
    end

    def edit
      @brand = Brand.find(params[:id])
    end

    def update
      brand = Brand.find(params[:id])
      brand.update(brand_params)
      redirect_to admin_brands_path
    end

    private

    def brand_params
      params.require(:brand).permit(:description)
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def models
    brand = Brand.find_by_name(params[:brand])
    @models = brand.models
    render json: @models.to_json
  end


end

app/views/admin/brands/_form.html.erb
<div class="form-group form-group-default">
  <%= f.label :description %>
  <%= f.text_area :description, id: 'wysiwyg5', class: 'wysiwyg form-control', placeholder: 'Describe the brand..', required: true, style: 'height: 250px;' %>
</div>

app/views/admin/brands/edit.html.erb
<!-- START PAGE COVER -->
<div class="container-fluid container-fixed-lg ">
  <ul class="breadcrumb">
    <li>
      <p><%= link_to 'Home', admin_root_path %></p>
    </li>
    <li><a href="" class="active">Edit Brand</a></li>
  </ul>
  <!-- END BREADCRUMB -->
  <h3 class="page-title">Edit Brand: <%= @brand.name %></h3>
</div>

<div class="container-fluid container-fixed-lg">
  <%= form_for @brand, url: {action: :update}, html: {class: 'form'} do |f| %>
      <%= render partial: 'admin/brands/form', locals: {f: f} %>
      <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

<% content_for :footer do %>
    <script>
        $(document).ready(function() {
            $('#wysiwyg5').wysihtml5();
        });
    </script>
<% end %>

app/views/admin/brands/index.html.erb
<!-- START PAGE COVER -->
<div class="container-fluid container-fixed-lg ">
  <ul class="breadcrumb">
    <li>
      <p><%= link_to 'Home', admin_root_path %></p>
    </li>
    <li><a href="#" class="active">Brands</a></li>
  </ul>
  <!-- END BREADCRUMB -->
  <h3 class="page-title">Brands</h3>
</div>

<div class="container-fluid container-fixed-lg">
  <%= form_tag update_multiple_admin_static_texts_path, method: :put do %>
      <table id="myDataTable" class="table table-hover" cellspacing="0" width="100%">
        <thead>
        <tr>
          <th>Naam</th>
          <th>Slug</th>
          <th>Acties</th>
        </tr>
        </thead>
        <tbody>
        <% @brands.each do |brand| %>
            <tr>
              <td><%= brand.name %></td>
              <td><%= brand.slug %></td>
              <td>
                <%= link_to 'Edit', edit_admin_brand_path(brand), class: 'btn btn-info' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>


  <% end %>
</div>

<% content_for :footer do %>
<% end %>