config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  mount RailsAdmin::Engine => '/railsadmin', as: 'rails_admin'
  devise_for :users

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root 'cars#home'

  get 'finance.php' => redirect('cars/financing/bussiness')
  get 'finance-form.php', controller: :cars, action: :finance_ash_car

  resources :cars do
    collection do
      get :search
      post :search
      get :nieuw_binnen
      get 'financing/:type', to: :financing, as: :financing
      get :voorraad, action: :index
      get 'finance_ash_car/:car/:type', to: 'cars#finance_ash_car'
    end
  end

  resources :brands do
    collection do
      post :models
    end
    resource :cars do
      get :index, to: 'cars#brand'
    end
  end

  resources :models do
    resource :cars do
      get :index, to: 'cars#model'
    end
  end

  resource :faqs do
    get :index
  end

  resource :wizard do
    post :pick_a_car
    get :pick_a_car
    post :your_details
    post :final
  end

  resources :pages, only: [:show] do
    collection do
      get :contact
      get :sitemap
    end
  end

  resources :blog_pages do
    collection do
      get :auto_blog
      get :auto_lease_mogelijkheden
      get :auto_op_afbetaling
      get :full_operational_lease
      get :lease_gebruikte_autos
      get :opel_eyetracking
      get :our_workspace
      get :voordelen_financial_lease
    end
  end

  resources :action_pages, path: :action, only: [:show]

  resources :blog_pages, as: :blog, only: [:show]

  resources :references, only: [:index, :create]

  namespace :admin do
    resource :admin do
      get :home
    end

    resources :action_pages

    resources :cars, only: [:index, :destroy]
    resources :static_texts do
      collection do
        put :update_multiple
      end
    end
    resources :faqs
    resources :pages
    resources :blog_pages do
      collection do
        get 'new/:template', action: :new, as: :new_with_template
        get 'edit/:id/:template', action: :edit, as: :edit_with_template
      end
    end

    resources :top_reviews

    resources :brands

    resources :banners, path: :banner do
      post :update_row_order, on: :collection
    end

    resources :references, only: [:index, :destroy] do
      collection do
        get '/approve/:id', action: :approve, as: :approve
        get '/disapprove/:id', action: :disapprove, as: :disapprove
      end
    end

    resources :menu_items do
      collection do
        put :update_all
      end
    end

    resources :cms_fields, only: [:index, :update]

    resources :car_requests, only: [:index, :show, :destroy] do
      get :show_bussiness
      delete :destroy_bussiness
    end

    root 'static_texts#index'
  end

  post '/import', to: 'import#handle'

end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController

  layout false

  def pick_a_car
    comparison_price_field = params[:total_value_slider] == 'true' ? 'price_50_50' : 'price_month'
    default_range = params[:min] + '-' + params[:max]
    if params[:total_value_slider] == 'true'
      @total_range = default_range
    else
      @month_range = default_range
    end
    @cars = Car.includes(:brand, :model).where("#{comparison_price_field} >= :min_price AND #{comparison_price_field} <= :max_price", min_price: params[:min], max_price: params[:max])
    @cars = @cars.where(brand: {name: params[:brand]}) if params[:brand].present?
    @cars = @cars.where(model: {name: params[:model]}) if params[:model].present?
    @cars = @cars.page(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def your_details
    @car = Car.find(params[:id])
  end

  def final
    klass = params[:request_type] == 'financial' ? CarRequestBusiness : CarRequest
    request = klass.create((params[:request_type] == 'financial' ? send(:car_request_bussiness_params) : send(:car_request_params)))
    CarRequestMailer.send_mail(request, request.email).deliver
    CarRequestMailer.send_mail(request, 'info@autokredietplan.nl').deliver
    track_event 'cars', 'finance request ingedient', request.car.display_name, params[:request_type]
  end

  private

  def car_request_params
    params.permit(:request_type, :payment, :name, :amount, :phone, :license_plate, :email, :bkr, :net_income, :partner_net_income, :rent, :car_id, :newsletter_subscribe, :bkr, :woonachtig)
  end

  def car_request_bussiness_params
    params.permit(:request_type, :payment, :first_name, :last_name, :amount, :phone, :email, :kvk, :car_id, :notes, :newsletter_subscribe, :date_creation, :woonachtig)
  end

end

app/views/wizards/_pick_a_price.html.erb
<div class="<%= if defined? positioned_home_page and positioned_home_page;
                  '';
                else
                  ; 'wizard';
                end %>">

  <section class="private-financing <%= if defined? positioned_home_page and positioned_home_page;
                                          'on-homepage';
                                        else
                                          ; '';
                                        end %>" data-car-url="<%= your_details_wizard_path %>">
    <div class="wrapper">
      <form action="" autocomplete="off">

        <input type="hidden" name="brand" value="<%= params[:brand] %>"/>
        <input type="hidden" name="model" value="<%= params[:model] %>"/>

        <h2><%= StaticText.send type + '_financing_header' %></h2>

        <p>
          <%= StaticText.send type + '_financing_head' %> <br/>
          <%= StaticText.send type + '_financing_head_2' %> <br/>
          <%= StaticText.send type + '_financing_head_3' %>
        </p>

        <%= render 'wizards/steps', step: 1 unless defined? positioned_home_page and positioned_home_page == true %>

        <% if defined? positioned_home_page and positioned_home_page %>
            <div class="model_brand_container row row-1">

              <h3>Please select a brand and a model</h3>

              <p class="select">
                <%= collection_select :q, :brand, Brand.all, :name, :name, {include_blank: 'Selecteer merk'}, {:class => 'search-advanced-brand', 'data-models-url' => models_brands_path} %>
              </p> <!-- .select -->

              <p class="select">
                <select class="search-advanced-model" name="q[model]" autocomplete="off" id="q_model">
                  <option value="">Selecteer model</option>
                </select>
              </p>
            </div>
        <% end %>

        <div class="slider-container">

          <input type="hidden" value="<%= type %>" name="wizard_type"/>

          <% if type == '50_50' %>
              <div class="slider-range" data-min="0" data-max="100000" data-spacing="100" data-default="0-100000"></div>
              <input id="price_slider_indicator" type="hidden" name="total_value_slider" value="1"/>
          <% else %>
              <div class="slider-range" data-min="0" data-max="1000" data-spacing="10" data-default="0-1000"></div>
          <% end %>

          <h3>
            <% if type == '50_50' %>
                <%= StaticText.wizard_main_slider_50_50_text %>
            <% else %>
                <%= StaticText.wizard_main_slider_text %>
            <% end %>
          </h3>

          <a class="btn btn-big first-step" data-next-step="<%= pick_a_car_wizard_path %>" href="<%= financing_cars_path "private" %>"><%= StaticText.wizard_main_slider_button %></a>
        </div>
        <!-- .slider-container -->

        <div class="footer">
          <i class="icon arrow-orange-down"></i>
        </div>
        <!-- .footer -->
      </form>
    </div>
    <!-- .wrapper -->
  </section>
  <!-- .private-financing -->

</div> <!-- /.wizard -->

app/views/wizards/_steps.html.erb
<div class="steps">
  <div class="step first complete">
    <%= StaticText.wizard_step_1 %>
  </div> <!-- .step -->

  <span class="icon steps-separator"></span>

  <div class="step <%= step > 1 ? 'complete' : '' %> <%= step == 1 ? 'selected' : '' %>">
    <%= StaticText.wizard_step_2 %>
  </div> <!-- .step -->

  <span class="icon steps-separator"></span>

  <div class="step <%= step > 2 ? 'complete' : '' %> <%= step == 2 ? 'selected' : '' %>">
    <%= StaticText.wizard_step_3 %>
  </div> <!-- .step -->

  <span class="icon steps-separator"></span>

  <div class="step <%= step > 3 ? 'complete' : '' %> <%= step == 3 ? 'selected' : '' %>">
    <%= StaticText.wizard_step_4 %>
  </div> <!-- .step -->

  <span class="icon steps-separator"></span>

  <div class="step last <%= step == 4 ? 'complete' : '' %>"></div> <!-- .step -->
</div> <!-- .steps -->

app/views/wizards/final.html.erb
<section class="wizard-final">
  <div class="wrapper">

    <%= render 'wizards/steps', step: 4 %>

    <div class="check">
      <i class="icon steps-final"></i>
    </div> <!-- .check -->

    <h2><%= StaticText.wizard_success_line_1 %></h2>
    <h3><%= StaticText.wizard_success_line_2 %></h3>

  </div> <!-- .wrapper -->
</section> <!-- .wizard-form -->

<%= render 'layouts/google_conversion' %>

app/views/wizards/pick_a_car.html.erb
<section class="wizard-cars">
  <div class="wrapper">

    <%= render 'wizards/steps', step: 2 %>

    <%= render partial: 'layouts/form_search' %>

    <div class="search-results">

        <%= render template: 'cars/search', locals: {results: false} %>

    </div> <!-- /.search-results -->

    <%= paginate @cars, :remote => true %>

    <div class="footer"></div> <!-- .footer -->

  </div> <!-- .wrapper -->
</section> <!-- .wizard-cars -->

<%= render 'layouts/google_conversion' %>

app/views/wizards/pick_a_car.js.erb
var carListing = $('ul.cars')
carListing.html('<%= escape_javascript render(partial: 'cars/car', collection: @cars, locals: {wizard_type: params[:wizard_type]}) %>');

$('nav.pagination').replaceWith('<%= escape_javascript paginate(@cars, :remote => true) %>');

$('.wizard .wizard-cars .search-results article.listing-car .goto a').on('click', function (e) {
    e.preventDefault();

    var $this = $(e.currentTarget),
            carId = $this.data('id'),
            nextStepUrl = $this.data('select-url');

    app.wizard.getCarForm($this, carId, nextStepUrl);
});

$('nav.pagination a').on('click', function() {
    $('nav.pagination').fadeTo('slow', 0.3);
});

helpers.scrollTo('.wizard .wizard-cars .search-results');

init.initCarSliders(carListing);
app.carListing.sameHeight(carListing);

app/views/wizards/your_details.html.erb
<section class="wizard-form">
  <div class="wrapper">

    <%= render 'wizards/steps', step: 3 %>

    <h2><%= StaticText.wizard_fill_the_details %></h2>

    <div class="form-container">

      <div class="left">
        <%= render @car, wizard_type: params[:wizard_type] %>
      </div>
      <!-- .left -->

      <div class="right">
        <form action="<%= final_wizard_path %>" method="post" class="payment-form">
          <input type="hidden" name="car_id" value="<%= @car.id %>"/>

          <p class="select">
            <select class="different" name="request_type" id="">
              <option value="financial" <%== if defined? params[:wizard_type] and params[:wizard_type].present? and params[:wizard_type] == 'bussiness';
                                               'selected="selected"';
                                             end %>>Zakelijk financieren
              </option>
              <option value="private" <%== if defined? params[:wizard_type] and params[:wizard_type].present? and params[:wizard_type] == 'private';
                                             'selected="selected"';
                                           end %>>Particulier financieren
              </option>

            </select>
          </p>
          <div class="normal_fields">
            <p class="text right" data-rules="required">
              <input type="text" name="payment" class="text" id="payment-payment"  value="<%== if defined? params[:wizard_type] and params[:wizard_type].present? and params[:wizard_type] == '50_50';
                                                                                                                    @car.price_50_50;
                                                                                                                  end %>"/>
              <label for="payment-payment">Aanbetaling</label>
            </p>

            <p class="text" data-rules="required">
              <input type="text" name="name" class="text" id="payment-name"/>
              <label for="payment-name">Naam</label>
            </p>

            <p class="text right" data-rules="numeric">
              <input type="text" name="amount" class="text" id="payment-amount"/>
              <label for="payment-amount">Te financieren bedrag</label>
            </p>

            <p class="text" data-rules="required|phone">
              <input type="text" name="phone" class="text" id="payment-phone" required="required"/>
              <label for="payment-phone">Telefoonnummer<small>(verplicht)</small></label>
            </p>

            <p class="text right" data-rules="required|email">
              <input type="email" name="email" class="text" id="payment-email" required="required"/>
              <label for="payment-email">Email<small>(verplicht)</small></label>
            </p>

            <p class="text" data-rules="required|numeric">
              <input type="text" name="net_income" class="text" id="payment-net-income"/>
              <label for="payment-net-income">Netto inkomen</label>
            </p>

            <p class="text right" data-rules="required">
              <input type="text" name="woonachtig" class="text" id="woonachtig" />
              <label for="woonachtig">Woonachtig in</label>
            </p>

            <p class="checkbox right" data-rules="required|alphanumeric">
              <input type="checkbox" name="bkr" class="checkbox" id="payment-bkr"/>
              <label for="payment-bkr">BKR geregistreerd?</label>
            </p>


            <p class="text" data-rules="required|numeric">
              <input type="text" name="partner_net_income" class="text"  id="payment-partner-net-income"/>
              <label for="payment-partner-net-income">Netto inkomen partner</label>
            </p>

            <p class="text" data-rules="required">
              <input type="text" name="rent" class="text"  id="payment-rent"/>
              <label for="payment-rent">Huur of hypotheeklasten</label>
            </p>
          </div>

          <div class="financial_fields" style="display:none;">

            <p class="text right" data-rules="required|email">
              <input type="email" name="email" class="text" id="payment-email" required="required"/>
              <label for="payment-email">Email<small>(verplicht)</small></label>
            </p>

            <p class="text" data-rules="required|phone">
              <input type="text" name="phone" class="text" id="payment-phone" required="required"/>
              <label for="payment-phone">Telefoonnummer<small>(verplicht)</small></label>
            </p>

            <p class="text right" data-rules="numeric">
              <input type="text" name="amount" class="text" id="payment-amount"/>
              <label for="payment-amount">Te financieren bedrag</label>
            </p>

            <p class="text" data-rules="required">
              <input type="text" name="first_name" class="text" id="payment-name-first" />
              <label for="payment-name-first">Voornaam</label>
            </p>

            <p class="text right" data-rules="required">
              <input type="text" name="last_name" class="text" id="payment-name-last" />
              <label for="payment-name-last">Achternaam</label>
            </p>

            <p class="text" data-rules="required|numeric">
              <input type="text" name="payment" class="text" id="payment-payment" />
              <label for="payment-payment">Aanbetaling</label>
            </p>

            <p class="text right" data-rules="required">
              <input type="text" name="kvk" class="text" id="payment-kvk" />
              <label for="payment-kvk">KvK Dossiernummer</label>
            </p>

            <p class="text">
              <input type="text" name="date_creation" class="text" id="payment-creation"/>
              <label for="payment-creation">Datum oprichting</label>
            </p>

            <p class="text right">
              <input type="text" name="notes" class="text" id="payment-notes" />
              <label for="payment-notes">Opmerking</label>
            </p>

            <p class="text" data-rules="required">
              <input type="text" name="woonachtig" class="text" id="woonachtig" />
              <label for="woonachtig">Woonachtig in</label>
            </p>

          </div>

          <p class="checkbox right">
            <input type="checkbox" name="newsletter_subscribe" class="checkbox" id="payment-newsletter-subscribe" checked="checked"/>
            <label for="payment-newsletter-subscribe">Inschrijven nieuwsbrief</label>
          </p>

          <p class="image right">
            <%= image_tag 'let-op-geld-lenen-kost-geld.jpg' %>
          </p>

          <p class="big-text last">
            Uw nieuwe auto, zo dichtbij!
          </p>

          <p class="submit right last">
            <button class="btn btn-small"><%= StaticText.wizard_submit_form %></button>
          </p>
        </form>
      </div>
      <!-- .right -->

    </div>
    <!-- .form-container -->

  </div>
  <!-- .wrapper -->
</section> <!-- .wizard-form -->

<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
    switch_form_fields();

    $('select[name="request_type"]').on('change', function () {
      switch_form_fields();
    });

  });

  function switch_form_fields() {
    var
        form_type = $('select[name="request_type"]').val(),
        financial_container = $('div.financial_fields'),
        normal_container = $('div.normal_fields');

    if (form_type == 'financial') {
      financial_container.show();
      normal_container.hide();
      $('[required="required"]', normal_container).prop('required', false);
      $('[required="false"]', financial_container).prop('required', 'required');
    } else {
      financial_container.hide();
      normal_container.show();
      $('[required="required"]', financial_container).prop('required', false);
      $('[required="false"]', normal_container).prop('required', 'required');
    }
  }

</script>